// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQh6LJJVckR2SjlUGrNk8jGOiO0TMT6gE',
    appId: '1:630395591429:web:da9af935195926d3f4356c',
    messagingSenderId: '630395591429',
    projectId: 'ipzparkinghunter-30f5b',
    authDomain: 'ipzparkinghunter-30f5b.firebaseapp.com',
    storageBucket: 'ipzparkinghunter-30f5b.appspot.com',
    measurementId: 'G-HKPSCYS913',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7MZszEW049XejNIEqMVvEj2UetQf5U30',
    appId: '1:630395591429:android:46e4ec1bdde0a2d3f4356c',
    messagingSenderId: '630395591429',
    projectId: 'ipzparkinghunter-30f5b',
    storageBucket: 'ipzparkinghunter-30f5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTjL6InQZRbCtxw5hbDbwTGZxc7HqsnJw',
    appId: '1:630395591429:ios:b49f900a81535179f4356c',
    messagingSenderId: '630395591429',
    projectId: 'ipzparkinghunter-30f5b',
    storageBucket: 'ipzparkinghunter-30f5b.appspot.com',
    iosBundleId: 'com.example.ipzParkinghunter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTjL6InQZRbCtxw5hbDbwTGZxc7HqsnJw',
    appId: '1:630395591429:ios:d6115ef402e79a60f4356c',
    messagingSenderId: '630395591429',
    projectId: 'ipzparkinghunter-30f5b',
    storageBucket: 'ipzparkinghunter-30f5b.appspot.com',
    iosBundleId: 'com.example.ipzParkinghunter.RunnerTests',
  );
}
